#
# Spring Properties
#
spring:
    #
    # Application Properties
    #
    application:
        name: reportwriter-program

    #
    # Just an non-web application
    #
    main:
        web-environment: false
        banner-mode: "off"


# Logging Properties
#
logging:
    file: ${LOG_FILE:rw_report.log}
    level:
        org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:ERROR}
        gov.nih.nci.evs.rw: ${LOGGING_LEVEL_GOV_NIH_NCI_EVS_RW:INFO}
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      console: ""

gov:
  nih:
    nci:
      evs:
       reportwriter:
         core:
           templateDirectory: ${RW_TEMPLATE_DIRECTORY:/tmp/templates}
           outputDirectory: ${RW_OUTPUT_DIRECTORY:/tmp/output}
         stardog:
           url: ${STARDOG_URL:http://localhost:5820/NCIT2}
           queryUrl: ${STARDOG_QUERY_URL:http://localhost:5820/NCIT2/query}
           username: ${STARDOG_USERNAME:ADMIN}
           password: ${STARDOG_PASSWORD:ADMIN}     
           readTimeout: ${STARDOG_READ_TIMEOUT:10000}
           connectTimeout: ${STARDOG_CONNECT_TIMEOUT:10000}
           graphName: ${STARDOG_GRAPH_NAME:http://NCI_T} 