#
# Spring Properties
#
spring:
    #
    # Application Properties
    #
    application:
        name: reportwriter-api 
    #
    # Data Source Properties
    #
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: ${RW_API_DATASOURCE_URL:jdbc:mysql://localhost/rw}
        username: ${RW_API_DATASOURCE_USERNAME:root}
        password: ${RW_API_DATASOURCE_PASSWORD:root}
        tomcat:
            initialSize: 10
            maxActive: 10
            maxIdle: 10
            validationQuery: SELECT 1 FROM DUAL
            testOnBorrow: true
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 10000
            minEvictableIdleTimeMillis: 60000
    data:
        rest:
          basePath: ${RW_API_BASE_PATH:/}
          defaultMediaType: application/json;charset=UTF-8
    #
    # JSON Formatting Properties
    #
    jackson:
        serialization:
            INDENT_OUTPUT: true
    #
    # JPA Properties
    #
    jpa:
        show-sql: ${RW_API_JPA_SHOW_SQL:true}
        hibernate:
            use-new-id-generator-mappings: true
#
# Server Properties
#
server:
    port: ${RW_API_SERVER_PORT:8080}

#
# Management Properties
#
management:
    contextPath: /admin

#
# Endpoint Properties
#
endpoints:
    mappings:
        enabled: true

#
# Logging Properties
#
logging:
    level:
        org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:INFO}
        org.springframework.boot: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT:WARN}
        org.springframework.data.jpa: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_JPA:WARN}
        org.springframework.data.rest: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REST:WARN}
        gov.nih.nci.evs.reportwriter: ${LOGGING_LEVEL_GOV_EVS_RW:INFO}
