gov:
 nih:
   nci:
    evs:
     reportwriter:
       core:
         templateDirectory: ${RW_TEMPLATE_DIRECTORY:/tmp/templates}
         outputDirectory: ${RW_OUTPUT_DIRECTORY:/tmp/output}
       stardog:
         url: ${STARDOG_URL:http://localhost:5820/NCIT2}
         queryUrl: ${STARDOG_QUERY_URL:http://localhost:5820/NCIT2/query}
         username: ${STARDOG_USERNAME:ADMIN}
         password: ${STARDOG_PASSWORD:ADMIN}
         readTimeout: ${STARDOG_READ_TIMEOUT:10000}
         connectTimeout: ${STARDOG_CONNECT_TIMEOUT:10000}
         graphName: ${STARDOG_GRAPH_NAME:http://NCI_T}

#
# Logging Properties
#
logging:
    level:
        org.springframework: INFO
        org.springframework.boot: WARN        
        gov.nih.nci.evs.reportwriter.core: INFO